# Generated by Django 4.1.1 on 2022-10-03 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': ('Category',),
                'verbose_name_plural': ('Categories',),
            },
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateTimeField(default='03-10-22')),
                ('due_date', models.DateTimeField(default='03-10-22')),
                ('category', models.ForeignKey(default='Random Task', on_delete=django.db.models.deletion.CASCADE, to='todolist.categories')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
